#!/bin/zsh

print "Installing Qogir_Mod themes"
./Qogir-theme/install

print "Installing solarized terminal theme"
dconf load /org/gnome/terminal/legacy/profiles:/:0bdff33e-e9ea-4b67-93ef-afab7fadea17/ < solarized-term.dconf

print "Removing Ubuntu Dock"
cd /usr/share/gnome-shell/extensions
sudo mv ubuntu-dock@ubuntu.com{,.bak}

print "Please remember to enable Qogir_Mod and solarized terminal themes"
