#!/bin/zsh

echo "Installing Qogir_Mod themes"
zsh ./Qogir-theme/Install

echo "Loading Gnome preferences"
dconf load / < dconf-settings.ini

echo "Removing Ubuntu Dock"
cd /usr/share/gnome-shell/extensions
sudo mv ubuntu-dock@ubuntu.com{,.bak}

echo "And we're done!"
