#!/bin/zsh

print "Installing Gnome extension integration and tweak tool"
sudo apt install gnome-tweak-tool chrome-gnome-shell

print "Please take the following steps manually:"
print "- Enable User themes"
print "- Install Dash to dock extension"
print "Afterwards, run setup2 to finish"
